workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      vars:
        SUPABASE_URL: "https://nssmzeiserockzavcsrh.supabase.co"
        SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zc216ZWlzZXJvY2t6YXZjc3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU2MTc4NjksImV4cCI6MjEwMTE5Mzg2OX0.YY2wynXVrRZxPdjMZRhNTolXGn3myJskhBQ7CdNO54I"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create .env file
        script: |
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          cat .env
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build unsigned iOS app
        script: |
          flutter build ios --release --no-codesign -t lib/main.dart
      - name: Package unsigned IPA
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/*.app Payload/
          zip -r unsigned.ipa Payload
    artifacts:
      - unsigned.ipa
