workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      vars:
        SUPABASE_URL: "https://frhemthvgbkjuthaoacx.supabase.co"
        SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyaGVtdGh2Z2JranV0aGFvYWN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY4MTk3OTcsImV4cCI6MjEwMjM5NTc5N30.XPq3w-BzMkwg7IzhbmCr2MAjoN0lYYbrpFeaa9Awz1k"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create .env file
        script: |
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          cat .env
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Generate code (freezed/json_serializable)
        script: |
          dart run build_runner build --delete-conflicting-outputs
      - name: Build unsigned iOS app
        script: |
          flutter build ios --release --no-codesign -t lib/main.dart
      - name: Package unsigned IPA
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/*.app Payload/
          zip -r unsigned.ipa Payload
    artifacts:
      - unsigned.ipa
