insert into public.exercises_library (name, muscle_group, equipment, is_custom)
values
  ('Press de banca', 'Pecho', 'Barra', false),
  ('Press inclinado con mancuernas', 'Pecho', 'Mancuernas', false),
  ('Aperturas con mancuernas', 'Pecho', 'Mancuernas', false),
  ('Fondos en paralelas', 'Pecho', 'Peso corporal', false),
  ('Press militar', 'Hombros', 'Barra', false),
  ('Elevaciones laterales', 'Hombros', 'Mancuernas', false),
  ('Elevaciones frontales', 'Hombros', 'Mancuernas', false),
  ('Face pull', 'Hombros', 'Polea', false),
  ('Extensión de tríceps en polea', 'Brazos', 'Polea', false),
  ('Curl de bíceps con barra', 'Brazos', 'Barra', false),
  ('Curl martillo', 'Brazos', 'Mancuernas', false),
  ('Fondos de tríceps en banco', 'Brazos', 'Peso corporal', false),
  ('Dominadas', 'Espalda', 'Peso corporal', false),
  ('Remo con barra', 'Espalda', 'Barra', false),
  ('Jalón al pecho', 'Espalda', 'Polea', false),
  ('Remo en polea baja', 'Espalda', 'Polea', false),
  ('Peso muerto', 'Espalda', 'Barra', false),
  ('Sentadilla', 'Piernas', 'Barra', false),
  ('Prensa de piernas', 'Piernas', 'Máquina', false),
  ('Zancadas', 'Piernas', 'Mancuernas', false),
  ('Extensión de cuádriceps', 'Piernas', 'Máquina', false),
  ('Curl femoral', 'Piernas', 'Máquina', false),
  ('Elevación de gemelos', 'Piernas', 'Máquina', false),
  ('Hip thrust', 'Glúteos', 'Barra', false),
  ('Plancha abdominal', 'Core', 'Peso corporal', false),
  ('Elevación de piernas', 'Core', 'Peso corporal', false),
  ('Crunch abdominal', 'Core', 'Peso corporal', false),
  ('Russian twist', 'Core', 'Peso corporal', false);
